// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy-GLYGlOzxKJJQx46iM96uoqO3ru87n0',
    appId: '1:477613903102:web:3d95e6a1c34465e3d5a9af',
    messagingSenderId: '477613903102',
    projectId: 'fruit-hub-e5473',
    authDomain: 'fruit-hub-e5473.firebaseapp.com',
    storageBucket: 'fruit-hub-e5473.firebasestorage.app',
    measurementId: 'G-D7TEXXP8S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiRvVBGf0zpJFNTtF5NLEkGD37pVkuaFU',
    appId: '1:477613903102:android:cde21eba0f98581cd5a9af',
    messagingSenderId: '477613903102',
    projectId: 'fruit-hub-e5473',
    storageBucket: 'fruit-hub-e5473.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1a2fbL2DO17m6oCWTgfMnHkD8mOuP88',
    appId: '1:477613903102:ios:bb2ce9deaf7db816d5a9af',
    messagingSenderId: '477613903102',
    projectId: 'fruit-hub-e5473',
    storageBucket: 'fruit-hub-e5473.firebasestorage.app',
    androidClientId: '477613903102-t3m035t43ct7vf2c2mt6k4866c5bdg79.apps.googleusercontent.com',
    iosClientId: '477613903102-69gd4jd5cmqgouc76vohqgmfrg20bb4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.frutHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1a2fbL2DO17m6oCWTgfMnHkD8mOuP88',
    appId: '1:477613903102:ios:bb2ce9deaf7db816d5a9af',
    messagingSenderId: '477613903102',
    projectId: 'fruit-hub-e5473',
    storageBucket: 'fruit-hub-e5473.firebasestorage.app',
    androidClientId: '477613903102-t3m035t43ct7vf2c2mt6k4866c5bdg79.apps.googleusercontent.com',
    iosClientId: '477613903102-69gd4jd5cmqgouc76vohqgmfrg20bb4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.frutHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy-GLYGlOzxKJJQx46iM96uoqO3ru87n0',
    appId: '1:477613903102:web:544d65c4cd0abe14d5a9af',
    messagingSenderId: '477613903102',
    projectId: 'fruit-hub-e5473',
    authDomain: 'fruit-hub-e5473.firebaseapp.com',
    storageBucket: 'fruit-hub-e5473.firebasestorage.app',
    measurementId: 'G-W13FJZGS7Y',
  );
}
